[platformio]
default_envs = uno

[env]
build_flags =
  -std=gnu++17
test_framework = unity

[env:uno]
platform = atmelavr
board = uno
framework = arduino

[env:native]
platform = native
test_build_src = no
